package com.example.userdata;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Favorite.
 */
public class Favorite {

    private Long creationDate;
    private Long externalId;
    private String object;
    private String searchName;
    private Long sortOrder;

    public Favorite() {
    }

    public Favorite(Long creationDate, Long externalId, String object, String searchName, Long sortOrder) {
        this.creationDate = creationDate;
        this.externalId = externalId;
        this.object = object;
        this.searchName = searchName;
        this.sortOrder = sortOrder;
    }

    public Long getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Long creationDate) {
        this.creationDate = creationDate;
    }

    public Long getExternalId() {
        return externalId;
    }

    public void setExternalId(Long externalId) {
        this.externalId = externalId;
    }

    public String getObject() {
        return object;
    }

    public void setObject(String object) {
        this.object = object;
    }

    public String getSearchName() {
        return searchName;
    }

    public void setSearchName(String searchName) {
        this.searchName = searchName;
    }

    public Long getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Long sortOrder) {
        this.sortOrder = sortOrder;
    }

}
